ALTER TABLE CONTACT DROP CONSTRAINT CONTACTcustomer_id
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMERindustryid
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMERnormalUser
DROP TABLE ALLUSER
DROP TABLE CONTACT
DROP TABLE CUSTOMER
DROP TABLE INDUSTRY
